config/routes.rb
Rails.application.routes.draw do
	root 'items#index', as: 'home'
	get 'about' => 'pages#about', as: 'about'

	resources :items do
		resources :comments
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :comments
  validates :title, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @item = Item.find(params[:item_id])
    @comment = @item.comments.create(comment_params)
    redirect_to item_path(@item)
  end

  private
    def comment_params
      params.require(:comment).permit(:username, :body)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "111",
    except: [:index, :show]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if(@item.update(item_params))
      redirect_to @item
    else
      render 'new'
    end
  end

  def create
    @item = Item.new(item_params)
    if(@item.save)
      redirect_to @item
    else
      render 'new'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  private
    def item_params
      params.require(:item).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/items/edit.html.erb
<h2>Редагуввання товар</h2>
<%= form_for :item, url: item_path(@item), method: :patch do |f| %>
  <% if @item.errors.any? %>
    <% @item.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    Назва товару<br>
    <%= f.text_field :title, {class: 'form-control'}%>
  </p>
  <p>
    Опис<br>
    <%= f.text_area :body, {class: 'form-control'}%>
  </p>
  <p>
    <%= f.submit({class: 'btn btn-success'}) %>
  </p>
<% end %>

app/views/items/index.html.erb
<h1>Усі наші товари</h1>
<% @items.each do |item| %>
  <div class="alert alert-light">
    <h3><%= item.title %></h3>
    <p><%= item.body %></p>
    <%= link_to "Читати", item_path(item), :class => 'btn btn-warning' %>
  </div>
<% end %>

app/views/items/new.html.erb
<h2>Новий товар</h2>
<%= form_for :item, url: items_path do |f| %>
  <% if @item.errors.any? %>
    <% @item.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    Назва товару<br>
    <%= f.text_field :title, {class: 'form-control'}%>
  </p>
  <p>
    Опис<br>
    <%= f.text_area :body, {class: 'form-control'}%>
  </p>
  <p>
    <%= f.submit({class: 'btn btn-success'}) %>
  </p>
<% end %>

app/views/items/show.html.erb
<h1><%= @item.title %></h1>
<p><%= @item.body %></p>
<hr>
<%= link_to "Редагувати", edit_item_path(@item), :class => "btn btn-warning" %>
<%= button_to 'Видалити', @item, method: :delete, form: 
  { data: { turbo: true, turbo_confirm: 'Are you sure?' } }, :class => "btn btn-danger" %>
<hr>
<h2>Усі коментарі</h2>
<% @item.comments.each do |comment| %>
  <div class="alert alert-light">
    <h3><strong><%= comment.username %></strong>: <%= comment.body %></h3>
  </div>
<% end %>
<hr>
<h2>Новий коментар</h2>
<%= form_for ([@item,  @item.comments.build]) do |f| %>
  <p>
    Користувач<br>
    <%= f.text_field :username, {class: 'form-control'}%>
  </p>
  <p>
    Коментар<br>
    <%= f.text_area :body, {class: 'form-control'}%>
  </p>
  <p>
    <%= f.submit("Додати коментар", {class: 'btn btn-success'}) %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
        <span class="fs-4">Sence</span>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <span class="py-2 link-body-emphasis text-decoration-none"><%= link_to "Головна сторінка", home_path %></span>
        <span class="py-2 link-body-emphasis text-decoration-none"><%= link_to "Новий товар", new_item_path %></span>
        <span class="py-2 link-body-emphasis text-decoration-none"><%= link_to "Про нас", about_path %></span>
      </nav>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>We are the champions</h1>